"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var registroautomotor_1 = require("./registroautomotor");
var auto_1 = require("./auto");
var moto_1 = require("./moto");
var camion_1 = require("./camion");
var registro = new registroautomotor_1.RegistroAutomotor();
var auto1 = new auto_1.Auto("Toyota", "Corolla", 2020, 4);
var moto1 = new moto_1.Moto("Yamaha", "MT-07", 2021, "Deportiva");
var camion1 = new camion_1.Camion("Mercedes", "Actros", 2019, 15000);
registro.agregarVehiculo(auto1);
registro.agregarVehiculo(moto1);
registro.agregarVehiculo(camion1);
console.log(registro.getVehiculos());
